### ISSUE TITLE
Mechanical User Issue

### ISSUE THREAD

**Issue by DaBenjle** [scalda/FoolCraft#127]
I think Iskall mentioned this in one of his videos but he did not give a solution. When the mechanical user is on Entity mode (or maybe any mode not sure) and an item is on top of it it will crash the server. Not only that but it won't let you reopen the world without crashing.

**Comment by DaBenjle** [comment]
Update, here's the error code when it crashes.

The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.lang.RuntimeException: Error while interacting with block minecraft:air with 1xitem.bucket@0. Method:ENTITY  Button:RIGHT_CLICK

**Comment by sirfirehare** [comment]
I have a similar error, which started when i tried to right click a mechanical user with one of the weapon case loot swords in my hand, which crashed the world, when i try to open the world it crashes, and i tried restoring the world, but alot of the modded blocks that i had placed and some that were not placed by me had turned into other random modded blocks(berry bushes turning into planks, the mechanical users turned into mechanical miners) These are the crash reports from the original world.

[crash-2017-03-29_11.32.47-server.txt](https://github.com/scalda/FoolCraft/files/877798/crash-2017-03-29_11.32.47-server.txt)
[crash-2017-03-29_11.36.06-server.txt](https://github.com/scalda/FoolCraft/files/877799/crash-2017-03-29_11.36.06-server.txt)
[crash-2017-03-29_11.29.22-server.txt](https://github.com/scalda/FoolCraft/files/877800/crash-2017-03-29_11.29.22-server.txt)

**Comment by CriticalMole** [comment]
This is an issue within Extra Utilities and there is very little we can do on our side.
For prevention your best bets are to build your setup so the user is not facing up on the ground but rather have it one block off the ground facing sideways, then make it so you cannot walk in the block directly in front of it.
As for worlds that have fallen victim if the chunk is claimed via FTB utilities you may be able to go into the config and change "Allow Fake Players" to false in order to get back in.
Beyond that it is a case of restore from back up or MCedit your world to remove the mechanical user

**Comment by SanShiBashi** [comment]
Another recovery process: disable the extra utilities mod (using the twitch launcer: Click the foolcraft profile, Click '...' in upper right, click 'profile options', remove the check in front of 'Locked') and launch the game. Make sure to visit the places in-game where the offending mechanical users are, and quit the game. Enable the extra utilities mod, start the game again and replace the mechanical users.
If you feel the need of correcting a lot of damage while playing this as a single player survival, use the 'open to LAN-allow cheats-gamemode c' trick to do this in game, without the need of learning MCEdit.
