### ISSUE TITLE
Suggestion FoolCraft

### ISSUE THREAD

**Issue by SirDizarm** [scalda/FoolCraft#149]
Log's with bark on all sides, that way we who make Chisel & Bit designs have more blocks to use for roof etc. 
Like:
![untitled-3](https://cloud.githubusercontent.com/assets/22151944/24560801/7afb19a0-1644-11e7-87bc-b1ad2bc436eb.png)

Its not something that are ingame atm, had to photoshop.

**Comment by Tumil** [comment]
Chests that doesn't need there to be air block over to have it store item, same with us Chisel & Bit designers that want to hide things like ugly chests, have to put them somewhere else. 
![untitled-4](https://cloud.githubusercontent.com/assets/22151944/24560996/59ef6670-1645-11e7-8925-f84b24060cff.png)

Working chest with an vacuum hopper inside to act as a storage. Not the finest but it's something better then the normal chest.

**Comment by Cat09** [comment]
I don't think this is really the place for these thoughts, although they are nice ones, those things likely require a full mod file rather than tweaking current ones. I would submit the request to either chisel or BoP I think (assuming you thoroughly checked the _chisel_ options, check them on the off chance you haven't).
For the chests, that's a neat solution. check decocraft, some of those items, like cupboards have storage.

**Comment by Jo-Mamma75** [comment]
@SirDizarm 
@Cat09 is correct.  This request, although a great idea, is beyond the scope of our support.
