### ISSUE TITLE
Crash when trying to use Optifine.

### ISSUE THREAD

**Issue by vivalabrock** [scalda/FoolCraft#16]
I downloaded the modpack, I put the latest optifine in the mod folder and load up the game, it gets more than half way loading the mod and then just *CRASH* and I dont know why, since Iskall didnt seem to have a problem because he was using using it in his first video zooming in on things.. 

Any help would be greatly appreciated :)

**Comment by jiminycrickt** [comment]
Try using the D6 version of optifine, works fine for me :) i had same problem tho xD and apparently the latest optifine crashes 1.7.10 modpacks as well. I had figured I'd update another pack that i'm playing while installing optifine for FoolCraft, turns out I could have just copy pasted from one of my other packs instead xD

**Comment by vivalabrock** [comment]
Seriously? I also had someone tell me they removed Malasis Doors and it also worked.. but Ill give the D6 version a try. THANKS FOOL! :P

**Comment by scalda** [comment]
D6 is the confirmed version that works, it's the version we used all through testing.
