### ISSUE TITLE
NEI is incompatible with chisel

### ISSUE THREAD

**Issue by Hoff2567** [scalda/FoolCraft#197]
Opening a chisel(Unsure of others I tried the iChisel) causes a CTD. I'm also fairly certain NEI is incompatible with Optifine if that is also worth noting. Not sure what the point of having NEI in the pack was anyway.

**Comment by Lorenzo0404** [comment]
What version of optifine are you using? Try using ''OptiFine 1.10.2 HD U D6''.

**Comment by Mrbysco** [comment]
The iChisel crash is NEI's fault. It's a known issue.
https://github.com/TheCBProject/NotEnoughItems/issues/42

I know there is an update to NEI and CodeChickenCore but I'm not sure if it fixes it.

The probably reason NEI is still in the pack is due to some people liking the NEI interface better, and some use the cheaty magnet mode and other buttons

**Comment by scalda** [comment]
Also the ichisels recipe is disabled in the pack

**Comment by scalda** [comment]
fixed in 1.3
