### ISSUE TITLE
SUGGESTION - Quarry from ExUtil2

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#243]
Hi, I don't have perms to add tags but, it would be awesome if you could get iskallium via the miner from Extra Utils. It would make power so much easier as there is no good other way to generate power.

**Comment by Jo-Mamma75** [comment]
@CakeArmy 
I'm going to tag this as an "enhancement" and tell you that I've already spoke with @WinterGrave about adding the ability to add dimensions to the ore spawning of Iskallium.  For the purposes of the FoolCraft modpack though, even if we had the ability to add it to another dimension, we wouldn't.  The entire reason we removed the blocks of Iskallium from the Lootbags dropped by Wither Boss' is because the whole idea of the mod was to make the ore extremely rare.  Being able to mine it with a Quantum Quarry kind of defeats that intention.
For now, I am going to close this issue.  Keep an eye out for future versions of the Iskallium Reactors mod to see if the dimension IDs are implemented.
