### ISSUE TITLE
game just freezes.

### ISSUE THREAD

**Issue by redstoneguy10ls** [scalda/FoolCraft#283]
OK so the game is working for a few seconds then i try to place something down nope game just doesnt want to do anything anymore besides let me move around. i have 7.6G of ram using the curse launcher and i have a i7-6700HQ @ 2.60GHz

**Comment by Jo-Mamma75** [comment]
I have a default template setup for a reason.  I'm pretty sure, in fact, it specifically says not to change or remove any of the text.

**Comment by redstoneguy10ls** [comment]
honestly I don't give a crap anymore your stupid mod pack is so freaken messed up that nobody can even play it and the developers are just assholes that don't even care about there community. and yeah I did find a solution, IT'S CALLED DELETING THE WORLD AND STARTING OVER BECAUSE THE F***EN DEVELOPERS DON'T GIVE A F*** ABOUT YOU!

**Comment by legodude17** [comment]
@redstoneguy10ls Please be respectful

**Comment by Jo-Mamma75** [comment]
@redstoneguy10ls 
No no, don't hold back. Tell us how you really feel.
I closed the issue because you deleted the template which is there to help us not having to go through and ask the same stupid questions on each issue.  You're more than welcome to go open a new issue, use the template, fill it in completely and then we will be more than happy to try to assist.  I don't know what your particular problem is (other than being an over-entitled asshat complaining about something provided for free).  I play this pack just fine on a crappy office workstation with an i5, 8GB of RAM and a crappy Radeon HD7570 graphics card.  So for you to come in and delete the template, just state "I can't do anything" and "here are my computer specs" doesn't really help much.
