### ISSUE TITLE
Recipe issues / mod request / late game quickly..

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#301]
## SUGGESTION/HELP
- [ x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Recipes for draconic staff of power not in JEI (the upgrades do not show up, but do for others. Press u)
Quartz in alloy smelter does not yield silicon.
Please update woot in 1.3 so I can have a dragon farm.
End Game:
I got there pretty quick. Do not continue reading if you want to know how to "beat" pack

Make capacitor banks to store aleast 1mill rf 
Make about 64 nether star generators, cheap with quick auto wither farm. I have one that spawns withers every 8 seconds with a Max of 10 withers at once but is easily scaleable.
Make tier 4 woot farm for wither
Restart game/server 
Mass and speed upgrade recommended
Make more generators as needed
You now get:

About 10 withers per minute, although you can get more with upgrades
I produce about 100k rf/t after running my farms, huge refined storage system, dragon woot farm & wither woot farm. 
I feel this should be changed. I did update woot myself for the dragon farm, but that does not affect power production, just consumption.
I feel getting to late game is too easy. Maybe scale back on unbreakable picks? Limit to 4 reinforcements? It would slow down the easy to grind and beat system of veinmining for 2hours on bedrock and being set.

## Additional Information
Can provide screenshots of setup

**Comment by CakeArmy** [comment]
Disclaimer: typed on phone

**Comment by Jo-Mamma75** [comment]
Not all features in Draconic Evolution have been fully implemented but the mod author is working on it.
Quartz will make silicon in the alloy smelter if it is on the correct setting (i.e. Furnace not All Smelting or Alloy).  You can also make it by running sand through a SAG Mill.
Dragon in Woot?  No  (and you're complaining about the pack being "too easy")
Tinkers Pick Not Unbreakable?  No
The pack is only "beatable" if you want it to be.  Maybe you should exhibit some self-control.
Play with these two things in the back of your mind.
1) Just because you can, doesn't mean you should.
2) How much crap do you really need?
Some people's late game are other people's beginning (i.e. people who want to spend the time actually building things rather than gathering resources like a madman and stuffing them into a storage system)

**Comment by CakeArmy** [comment]
Woah. I was not expecting that. Me have self control? Mmk. Considering I
have not used the loot from it, and it didn't affect my acceleration in the
pack. The reason for me doing this was if let's say you wanted to fight the
chaos dragon... you need about 50 dragon hearts. No way to kill dragons
fast, it's too grind imo. The cost in power is high so that tries to
balance it.

**Comment by legodude17** [comment]
@CakeArmy I thought you were complaining about there not being enough grind?

**Comment by CakeArmy** [comment]
No. I am saying I was hoping there would be MORE mods. More things to do with power. I mean, after you have steady power, you can easily run tons of machines and you rf system the only other thing to do would be building. I was trying to get more mods added, so there are more things tech-related that can be done.
