### ISSUE TITLE
Java crashing on loading screen.

### ISSUE THREAD

**Issue by MinerSass670** [scalda/FoolCraft#312]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I reported this on this forum already but still haven't been able to fix the problem. Java SE binary crashes during loading screen on every 1.10 modpack I try to play. I have tried reinstalling java and have also uninstalled the older versions. I have reinstalled the  Foolcraft modpack several times, still no use. Someone suggested to install the older version of Java because the newer version might have been causing the problem, but that didn't help.

## Reproduce Steps
By running Foolcraft.

## Additional Information
Problem Event Name: APPCRASH
Application Name: javaw.exe
Application Version: 8.0.1210.13
Application Timestamp: 584f5d7e
Fault Module Name: StackHash_51bf
Fault Module Version: 6.1.7601.18798
Fault Module Timestamp: 5507b864
Exception Code: c0000374
Exception Offset: 00000000000bf922
OS Version: 6.1.7601.2.1.0.256.1
Locale ID: 1061
Additional Information 1: 51bf
Additional Information 2: 51bf0f413302ea864d15886f465722c0
Additional Information 3: 2971
Additional Information 4: 2971e9cc7926d31411933c3fe6b5a407

Read our privacy statement online:
http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
C:\Windows\system32\en-US\erofflps.txt

**Comment by Jo-Mamma75** [comment]
This is probably something we can't help you with.  There is absolutely no telling what kind of issues you have with your computer and, although I do IT consulting for a living, I'm not at liberty to try to spend the time fixing what is clearly a computer problem rather than a problem with this particular modpack.  I apologize but this is outside the scope of support here.
My best advice, start searching Google for the errors and see what you can find.  Just be very careful of downloading anything to help "fix" it other than Java updates, Windows updates, etc.  If that doesn't do it, then you're looking at trying to take it to someone to have them fix it for you.
Sorry.  I wish you the best of luck with it.
