### ISSUE TITLE
Wither Spawner bug

### ISSUE THREAD

**Issue by MetaBender** [scalda/FoolCraft#313]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Wither spawner made from "Mob swab=GM chicken feed=spawner egg" on Vanilla blaze spawner. The spawner were placed in the nether to spawn wither skeletons. The wither spawner was working well for 2 days. And suddenly on the third day, after spawning wither skeletons for a few cycle, it suddenly stopped spawning them. Instead it spawns white skeletons. These white skeletons doesnt carry weapons. I tried relogging, restarting the game but the result was the same. It stopped spawning wither skeletons.

**Comment by Jo-Mamma75** [comment]
On the [Mob Grinding Utils CurseForge](https://minecraft.curseforge.com/projects/mob-grinding-utils) page, it specifically states the following:
"Note: Vanilla mobs with variants eg. Wither Skeletons, Husks and Donkeys are not supported in this version but are planned for the future. Some mods still don’t register their mob’s spawn eggs correctly and as a result some modded eggs will not work."

Your particular issue would be better suited for the mod author's [Github](https://github.com/vadis365/Mob-Grinding-Utils/issues) rather than here.
