### ISSUE TITLE
Server Crash On Start Up

### ISSUE THREAD

**Issue by BaneOfSmite** [scalda/FoolCraft#333]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
 
Server crash on start up

## Reproduce Steps

By starting the server, the crash is reproduced.

## Additional Information

Crash Report : https://pastebin.com/sELZ1Gg8

**Comment by BaneOfSmite** [comment]
Bump

**Comment by Jo-Mamma75** [comment]
It looks to be a an issue with an EnderIO Farming Station and a Vacuum Chest at coords (-268,54,212) and can be located in the r.-1.0.mca region file.  The best (and easiest) thing to do is to use MCEdit to just remove the block in question and then try loading the world again.  You can edit the world by getting only that region file and the level.dat file instead of downloading the entire world from your server.

**Comment by PSILONCRAFT** [comment]
i had a similar issue but with a nother blocktype. removed the blocks in mcedit rey-loaded the region and datafile, stil no bueno!.. have to do a rollback of the entire server to 1.2.2

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
