### ISSUE TITLE
Chunck Loader not working

### ISSUE THREAD

**Issue by aracnot** [scalda/FoolCraft#393]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by Maudslay** [comment]
I also second this because on a server i'm on i can't get it to work, I've noticed it was turned off but i need it on for my players to possibly keep their items online while they're off.

**Comment by ocarinaoftom** [comment]
Out of curiosity, are you referring to the FTB chunk loading? I ask because that was disabled in 1.3.2 and there is now a chunk loader item that has been enabled that you have to use instead. I originally missed that in the changelog and had the exact same problem until I set up the new chunk loading solution and now it works fine for me again.

**Comment by janagyjr** [comment]
I actually like the FTB chunk loader. I've not had any success with chunk loading items.

**Comment by Jo-Mamma75** [comment]
Yes, in the 1.3.2 update, FTB Utilities chunk loading was disabled and the configs for the Chicken Chunks chunkloaders were enabled.  Overall, we seem to have less problems with them than the FTB version.
Let me know if this resolves your issue otherwise I will close the issue automatically after a couple of days.

**Comment by scalda** [comment]
Please use chicken chunks
