### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by TrainGame** [scalda/FoolCraft#407]
[crash-2017-04-29_09.43.16-client.pdf](https://github.com/scalda/FoolCraft/files/965761/crash-2017-04-29_09.43.16-client.pdf)

**Comment by janf3** [comment]
`java.lang.OutOfMemoryError`
`JVM Flags: 3 total; -Xmx3072m -Xms256m -XX:PermSize=256m`
You need to assign more memory to Foolcraft. 3GB isn't enough to run Foolcraft. 
Try something between 4-6GB.
[https://github.com/scalda/FoolCraft/wiki/Up-the-ram-within-curse-launcher](url)

**Comment by TrainGame** [comment]
Thanks!

**Comment by TrainGame** [comment]
How do you change the RAM for Foolcraft/Twitch Launcher? The link doesn't work.

**Comment by janf3** [comment]
You should be able to set the Java memory in the Twitch Launcher Settings under Minecraft > Java Settings. Since I'm not using the launcher myself I'm not sure this is effective.

You can find the link I tried to post when you click on WIki at the top of this page, then on the right hand side "Up the ram within curse launcher". This method sets the RAM in the Minecraft Launcher and should definitely work.

**Comment by Ravalli03** [comment]
Yes, if you change the ram setting within the twitch launcher, (not the MC launcher), it will keep the Ram setting the same everytime you play.
