### ISSUE TITLE
World Type Issues

### ISSUE THREAD

**Issue by HivemindJak** [scalda/FoolCraft#412]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

## Issue Description
While in the world customization screen, I am unable to select and customize anything but Biomes O' Plenty for terrain gen. To be clear, I am trying to make a superflat world for mod testing. I attempted to choose superflat, then went to the customize screen to use a preset, but when I returned after clicking "Use Preset", the world gen type switches to Biomes O' Plenty. 

## Reproduce Steps
Steps are easily reproducible and are described in the Issue description.

**Comment by HivemindJak** [comment]
I did some digging in the configs (used to much older modded) and saw you could set the Biomes O' Plenty world type to default. I turned that off and it immediately fixed the issue. I later realized that I could do this from mods tab in the main menu. Side-note: Natura is spawning its Eucalyptus trees regardless of world type.

**Comment by HivemindJak** [comment]
Further note: editing the "Flat Sea Level" to higher than "Eucalyptus Range" yields no change.

**Comment by chland** [comment]
I can confirm the world type-bug. As soon as you try to customize the settings of any other world-type it will be reset to BoP as soon as you click on "Done" (i guess thats mostly a bug in BoP and should probably reported over there).

**Comment by janf3** [comment]
It was reported to BoP a long time ago but it seems the fix was only commited to the 1.11 branch/release. Glitchfiend/BiomesOPlenty#686

You can easily disable this setting in the BoP mod options ingame or by editing `FoolCraft/minecraft/config/biomesoplenty/misc.cfg` so not really a big issue.

As for the Eucalyptus thing I believe you have to disable Natura gen via `FoolCraft/minecraft/config/NaturaModules.cfg`

**Comment by HivemindJak** [comment]
I see, well thanks for the assistance! :)
