### ISSUE TITLE
Only one mod present in file version 1.3.3

### ISSUE THREAD

**Issue by vincentix** [scalda/FoolCraft#510]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

The only mod present in 1.3.3 is FoamFixLawful. Other mods are not even in the .zip file from curse

**Comment by ajdjyt** [comment]
what you are trying to use is the mods config code my friend,to get the actual pack install the twitch/curse launcher and then login into twitch or curse or sign up ,then go to the minecraft tab represented by a creeper face,then click "BROWSE ALL MODPACKS" then in the search bar type"foolcraft" then when it comes up hover your mouse on the photo and click install then wait for it to finish ,then click the creeper face again and click play under foolcraft and then the mc launcher will start then start the "forge-12.18.3..2281 - Foolcraft" and wait for it to load.....
then Voila !!!! Foolcraft should start for you

**Comment by spajky32** [comment]
You should download the server files from curse

**Comment by Jo-Mamma75** [comment]
If you are not using the Twitch/Curse launcher (or cannot use it) then you will need to download the server files as @spajky32 had mentioned and manually build your instance that way in MultiMC or whatever you plan on using.
I am going to close this issue though because you have been provided the information you need.
