### ISSUE TITLE
mca lasso wife crash

### ISSUE THREAD

**Issue by superon** [scalda/FoolCraft#519]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
i tried to move my wife out of the dungeon to somewhere when could stretch her legs, the golden lasso didn't workit, it did crash the client tho 

## Reproduce Steps
get wife, lasso wife

## Additional Information
https://pastebin.com/Htkyzzct

**Comment by legodude17** [comment]
I would suggest filing this on the Minecraft Comes Alive issue tracker.

**Comment by superon** [comment]
done, tho i now have a sinking feeling about being asked to post again on extraUtilities

**Comment by legodude17** [comment]
Maybe, were you shift clicking or just clicking?

**Comment by superon** [comment]
can't recall, sorry.  i think it's a regular right-click to use the lasso, if so that's likely what i did

**Comment by Jo-Mamma75** [comment]
The mod author for MCA has not updated the mod since last August and from what I've seen he doesn't care much about it or issues with it and frequently tries to blame them on other mods.  I wouldn't expect the issue to get resolved and as we don't develop the mod there is not really much we can do unfortunately.

**Comment by superon** [comment]
that's cool, at least it's not a fatal one like the infinity armour/chest remover thing: just don't lasso wife
 :)
