### ISSUE TITLE
Electrum tinkers' construct animation tanks FPS from ~80fps to ~25 fps

### ISSUE THREAD

**Issue by frenchiveruti** [scalda/FoolCraft#540]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

The Tinkers' Construct electrum pickaxe head has a property of becoming a shocking tool against any mob that you hit with it, the issue is that the animation of it looks like a big white mess that hits hard on my FPS in singleplayer, even without any "FPS improving" mods, such as Optifine or BetterFPS (foamfix is by default included on this version so I didn't try to disable it).

## Reproduce Steps
To reproduce, create a tool with electrum on it, and run a bit until is charged, then you'll see the issue.

## Additional Information
http://imgur.com/a/hnNGw
Here are two pics with the issue

**Comment by Jo-Mamma75** [comment]
I would imagine that this is an issue with Tinkers' Construct and since you've posted it there and are working it there, I will mention the issue here [SlimeKnights/TinkersConstruct#2968](https://github.com/SlimeKnights/TinkersConstruct/issues/2968)
That all said, its not something we can fix.  I do appreciate you opening the issue here though so if someone has the same issue they have something to hopefully give them a little more information.  However, I am going to close this issue.

**Comment by frenchiveruti** [comment]
No problem, I always try to leave the issues stated so they don't seem to appear random.
Thanks for understanding.
