### ISSUE TITLE
Update from 1.33 to 1.47 crash on startup

### ISSUE THREAD

**Issue by Tegwen** [scalda/FoolCraft#589]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

After the upgrade from 1.33 to 1.47 the game crashes on load with my saved world.  I tried to remove the profile from curse launcher and then re-load Foolcraft from scratch.  The I placed my save back into the save directory and it crashed on load again.  I have verified that both a new world and a different save, that my son plays, both load successfully.

Load game and it crashes.

Crash Report
https://pastebin.com/heAvkhF9

**Comment by PaternoX** [comment]
having same issue, tho cant retrieve a crash report. If its the nesting pens, im knackered (got 9 of every chicken in a nesting pen - see my foolcraft series on youtube)

Or if its the concrete mod, as someone else seems to have issue with, im knackered, as im using chisel n bits on concrete for my roads :/

**Comment by Tegwen** [comment]
I haven't used any concrete in my world.  But I do have at least 2 of each of the chickens that were available in 1.33.  I believe 1.47 added more, but I can't see how that would be an issue?  I used a bank of lava chickens for early game power and only recently finished up the rest of the chickens, all in nesting pens.

**Comment by chland** [comment]
The Hatchery-mod author changed quite a lot of things in the last couple of versions. And from what I remember he changed a lot of things regarding Nesting Pens and he messed up the IDs of the chickens at one point.

If I were you, I would probably make a backup of my world and try this "workaround": https://github.com/scalda/FoolCraft/wiki/Ticking-Block-Entity-fix-for-somethings-but-not-all-like-fluidcows - this will most likely destroy a bunch of your Nesting Pens but the world should work again. If it works, you could check what happens if you setup new pens. And don't forget to reset the forge-settings :)

**Comment by ValkyrieWings** [comment]
Thank you!

Julie Marshall

**Comment by Tegwen** [comment]
I was out of town but finally got a chance to try the suggestion above.  That seemed to work.  I am missing 2 pairs of chickens and all my nesting pens are facing different directions.  However now that I am able to get into my world, I can resolve that pretty easily.  Thanks for the help.  I am closing the issue.
