### ISSUE TITLE
Modern warfare ore not spawning

### ISSUE THREAD

**Issue by ShadowUnit2** [scalda/FoolCraft#616]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by ShadowUnit2** [comment]
I checked config of the pack and all the ore gen for this mod was set to 0 which prevents obtaining the materials nessesary to craft a lot of times in this mod

**Comment by EmperorSuper** [comment]
what i would do is get a storage drawer and ask an admin to give me one of the modern warfare's aluminum, then just put the aluminum from modern warfare in the drawer and then put aluminum from other mods into it too, once the aluminum is taken out it should all be a modern warfare aluminum

**Comment by ShadowUnit2** [comment]
im sorry but i can't MAKE an admin spawn me in stuff thats non obtainable so that doesn't fix the issue

**Comment by gahro-nahvah** [comment]
This is definitely a serious issue, preventing the use of a large aspect of an entire mod. It limits players to only using iron sights, and in some cases, guns cannot be crafted.

**Comment by EmperorSuper** [comment]
@ShadowUnit2 i didn't say you make an admin spawn it to you, i mean that as this is definitely an issue you might be able to get the servers' staff to create a way of converting other aluminum to the modern warfare aluminum.
i don't know what about you but that's a slightly better fix then waiting for it to be fixed in the modpack and then resetting the world so the ore spawns in my opinion.

**Comment by ShadowUnit2** [comment]
but as i said... aluminum isn't the only unobtainable thing so that wouldn't even work
