### ISSUE TITLE
Fun mod submissions for FoolCraft 2.0

### ISSUE THREAD

**Issue by scalda** [scalda/FoolCraft#629]
Hi, all here is the thread for the fun/pranky mod suggestions. 

Please use a very easy reading format for me to understand

Regards

Scalda

**Comment by SDCallo** [comment]
For mods, I suggest Mekanism. It's a great mod all around, but provides good power gen, tools/weapons, and machines.

**Comment by ptlthg** [comment]
Astral sorcery is a fun mod

**Comment by Lyzaid** [comment]
I would love to see Cyclic in Foolcraft.
Also Thaumic Potatoes could be a fun mod.
Maybe Headcrumbs

**Comment by janagyjr** [comment]
Ruins
Antique Atlas
Enchanting Plus
The Aether II 
Minecolonies
Extra Golems (you can never have enough running around)
Tinkers' Golem Addons
HermitBosses
RFTools Dimeions or Armora's Mining Dimension
Storage Drawers Extras since BoP adds so much wood
WitherCrumbs
Twitchcrumbs
Shear Madness looks funny

Fix Hermitron for Multiplayer or remove it

**Comment by MozzVader** [comment]
Platforms - https://minecraft.curseforge.com/projects/platforms

**Comment by spajky32** [comment]
Advanced rocketry

**Comment by AutisticMC** [comment]
JurassiCraft2.0 and Fossil and Archeology. plus thamucraft and better
questing

**Comment by Lyzaid** [comment]
Open Blocks would be a cool mod

**Comment by JTKillien** [comment]
Aroma1997s Dimensional World would be a nice addition, so we don;t have to "mess" up our would with vein miner strip mines.

**Comment by CaptainTransportation** [comment]
Minecraft Flight Simulator: https://minecraft.curseforge.com/projects/minecraft-flight-simulator

**Comment by chland** [comment]
Not a real suggestion/mod submission but a "thought":

Please don't add stuff like Minecraft Flight Simulator or Jurassicraft2 -> both mods hadn't any updates in 2017 - and thats never a good thing. 

And please don't add too many mods that are similar to existing mods. Antique Atlas for example is a nice mod but pointless if Journey Map is kept in the pack. Minecolonies is in a similar place if MCA stays in the pack (i know that they are different but both add a ton of stuff to villagers which is probably not the best thing to do).

**Comment by scalda** [comment]
Thanks for all the suggestions I have a finalised mod list now and I will
post when I am able to

**Comment by istoOi** [comment]
The Morph Mod is quite fun. http://www.mc-mod.net/morph-mod/

**Comment by svennieke** [comment]
@istoOi  I would stay away from those sites, downloads from those kind of sites don't support the mod developer and also these versions are mostly out of date or non existant, these sites may also come with a free virus or two.

i would higly suggest getting your mods from sites like:
https://minecraft.curseforge.com/
https://www.planetminecraft.com/resources/mods/
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods

**Comment by istoOi** [comment]
@svennieke thx for the suggestions. This site was just the first i found to show off the mod :)

**Comment by steamdemon1512** [comment]
Ender Compass and updated iextras

**Comment by Vivaldo37** [comment]
-
1. A Chisels and Bits bag that has an option to automatically pick up bits or auto refill bits in your inventory, also has unlimited storage and you can use to paste other designs from the bits inside the bag (maybe with a search bar built in. maybe with a scroll bar.)

2. ELECTRIC CHISEL (or some other name) A Chisels and Bits configuring tool with a hotkey (e.g. "L") to open options to select things such as:
- Copy and paste (duplicate) copy -> paste -> copy -> paste -> copy -> paste
- Cut and paste (move)
- Rotate (shift rotate vertical)
- Consume
- etc

3. Enchantment Cases. Also make enchantments applicable to mods that they normally aren't applicable to such as tinkers tools maybe just make them applicable to everything if that is possible because this is FOOL craft (doesn't make a lot of sense but yeah, vanilla enchantments get forgotten and unused mostly in modded).

4. All or some of the AE2 extras mods (if they are updated?)

5. A mod to make EnderIO and AE2 work smoothly together if needed..

**Comment by Larkal92** [comment]
Since this is open still, some of the things I'd like to see added are: 

Immersive Engineering 
Blood Magic 
Cyberware 
Everlasting Abilities 
Holographic Victory Monument 

Maybe add Avaritia components to loot bags or Roguelike chests if its going to stay.﻿

**Comment by colin500** [comment]
open security for OpenComputers :)

**Comment by ajdjyt** [comment]
I would love to see these mods in here
1.Akashic Tome
2.Mekanism
3.Mekanism Generators
3.Mekanism Tools
4. Open Computers
5. Aromas1997 Dimension-World
6. Actual Additions
7. Silent Gems
8. Immersive Engineering
9. Aether II
10. Big Reactors
11. Compacter
12. Better Questing Or HQM (Hardcore Questing Mod)
13. Galacticraft
14. Extra Planets
15. Open Blocks
16. Actually Computers
17. Clipboard
18. Extra Planets
are some i would like to see 
Lets Hope most of these get added and hope foolcraft 2.0 IS THE GREATEST MODPACK EVER 
And hope The Hermits Finish The Pack This Season!

**Comment by scalda** [comment]
suggestions is now closed since the pack is now released. thank you all
