### ISSUE TITLE
Mini Moo (Fool Cow) Dupe Glitch with Golden lasso (Foolcraft 2.3.1)

### ISSUE THREAD

**Issue by johnwolf01** [scalda/FoolCraft#813]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When Capturing Mini-Moo Cow that are "secretly" a Fool cow using a golden lasso. The "fake cow" goes into the lasso and the fool cow spawns. You can place the "fake cow" again as it is inside the lasso.
Using the lasso on the  re-placed "fake cow" again. spawns another Fool cow and the fake goes into the lasso again. This process can be repeated infinitely to spawn 1000's of "fool cows"

## Reproduce Steps
1. Use Golden Lasso on Mini Moo (Fake). Fool Mini moo Spawns and the lasso contains the "fake" mini moo.
2. Place fake mini moo from the lasso on the ground.
3. Re-capture the "fake" Mini Moo ( that was placed in step 2 ) with golden lasso. Another Fool mini moo spawns.
4. Repeat Steps 1-3 for infinite Fool mini Moo.

**Comment by RicardoTheCoder** [comment]
@johnwolf01 This should be fixed in the new update of the mod, thanks for pointing this out :)

**Comment by johnwolf01** [comment]
@RicardoTheCoder 

I have found something else but before I make a report I would like mention - I have not yet tested to see exactly where the problem is - but this is the situation..

I have a setup of automatic milking the cows using MFR Rancher.
the area is Chunk loaded by Both the FTB / Forge chunk loading "map" and the Chunk Loader from "Chickenchunks" 

But when I am to far away from the area, the cows are not being milked.
I do suspect it may have something to do with the cow's cooldown because chunk loading  works for both FBT and chickenchunks in other area's. I will add a vanilla cow along with the mini moo's 
and if that gets milked consistently it should prove its the mini moo Cooldown.

**Comment by johnwolf01** [comment]
Ive done the test with vanilla cow. The chunks are loaded by either above mentioned methods and rancher works. milking vanilla cows.

So chunk loading does not affect the mini moo's cool down or milking. 
a player has to be in range of the cows for them to be milked.

**Comment by RicardoTheCoder** [comment]
@johnwolf01 This should not happen in the new version of the mod as it uses a more reliable system to keep the values updates, however if this presists I might not be able to find the problem as on my foolcraft server it works with my chunkloader. They send the fluids into my casters and the blocks into the system.

But I should recheck that again just to be sure, thanks to pointing this out. Will get back to you when I can and try and find a solution to that problem, if possible.

**Comment by johnwolf01** [comment]
@RicardoTheCoder 
My method is as follow,
Rancher feeds into tinker Tanks, that cast out into casting basin. all are connected with Ender IO conduit.
when I "stop" the flow between the tanks and the caster, and afk with the cows, the tinker tanks fill up.
after draining them all. and I afk at my mob farm that are 90+ blocks away, for the same amount of time, the tanks are still fairly empty excluding for 2-3 buckets worth of molten material that was milked when arriving or leaving the area. At first I thought that it may be power, rancher or some other block not working, So I added a vanilla cow to the setup, and went afk at the mob farm again.
When returning, all tanks were empty except one that was filled to the top with milk.

So I came to the conclusion that the machine blocks, power and conduit  all work, but for some unknown , the mini's are not milked unless you are within at least 16 blocks
Thank you

**Comment by RicardoTheCoder** [comment]
@johnwolf01 Foolcraft released an update yesterday that should fix this (Also nice design gave me an idea for my base :P )

I changed the way moos store their values on the latest version of the mod and that should fix the problem. 

Your setup and mine is almost the same, except I send the fluids directly into a casting basin instead of going through the tinker tank. And for you to have an idea, I have the fluid moo farm in my old base, that is roughly 2 to 5 thousand blocks away of the new one. I have chunk loader from chickenchunks and from ftb in the area (I have both setup simultaneously, as I found that having both fixes problems from the chunks unloading unexpectedly). I also have the new base loaded in the same way, the casted blocks go into a chest that sends the blocks into my ME (AE2) Network, that arrives at my new base through Quantom Brigdes, Wireless Transmitters (from AE2 Stuff that I added to my server) or Dimensional Transceivers, I have tested the 3 options. Being only in my new base I can see the blocks getting added into the system and I have no other way of getting those blocks except for the moos, and I'm not even close to the moos in order to keep them "loaded" and I still get the blocks at a normal amount.

What I would suggest is for you to replace your ranchers (as they might be bugged because of the changes to the moos code) and try it again to see if it works. Also If you are in a server (that as the configs altered) you might want to check if the configs of the chunk loaders have been changed in any way as this might create problems that are not an issue related to my mod.

Also if your moos still seem to stay bugged, capture them with a animal net and release them as that should fix any issue they might have with their data. Any tests you do based on what I have said, to prevent problems I would suggest that you backup your world.

**Comment by johnwolf01** [comment]
Thank you for your effords and the info.
As for the tinker tanks usage , I have more than 2-3 cows per section thus creating more fluid than what some of the casters can handle, also due to the curing time of some metals. The tinker tanks is a huge buffer for the liquid, it is also a visual on what metal I have in surplus. in addition to that, I can also Auto-mix - alloys, - this method helps if you dont have for example a dark steel cow :+1: 
( ie, adding the following mini cows in the same milking station
water cow, Iron Cow and 2 lava cows. ( Water + lava = Obsidian)
 Obsidian + Lava + Iron = Dark steel ) Because there will be more lava one part will mix with water,
the other lava will remain to mix with iron when it is added and thus create dark steel.

additional tip.
When having more that one fluid in a tinker Tank or Smelter.

Use ender fluid conduits. When you pump out all fluid (type A) from the tinker tank/smelter to a secondary tank, and then back in to the primary tank, the fluid will go on top of other Fluids (type B) that exist in the tank. 

Setting your fluid conduit to In and Out - "active with redstone" you can Cycle between the fluids that exist in the tank, by sending redstone pulses on a slow timer to the ender conduit. Thus creating a cycle of casting every other metal on turn. This will allow you to have multiple cows filling the same tank without to much flooding. ( note ) that dont do this for fluids that mix creating a new alloy , unless you want to...

I will update asap . Thank you !!
