### ISSUE TITLE
Questbook - A Chicken Farmes Life / Chickens Poop What !!!

### ISSUE THREAD

**Issue by WonderDog** [scalda/FoolCraft#837]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Quest  - A Chicken Farmes Life / Chickens Poop What !!! requires a Flint Chick Egg from Chickens Mod.  Flint chickens drop hatchery eggs.

## FIX:

I edited the quest to use a Hatcherty Flint Chicken egg with stats 10/10/10 and it worked.

**Comment by svennieke** [comment]
thank you for bringing this to my attention, i will try to fix this quest, and if this is not a thing that can be done due to limitations or bugs in the mod, i will change the quest itself slightly as i remember the iron chicken eggs where glitched out in previous patches, beacuse the NBT was not detecting right. I hope your suggested fix will fix this issue as this would save a lot of time and work, thank you so much

**Comment by scalda** [comment]
this is now fixed in 2.5
