### ISSUE TITLE
2.5.1 ChickenChunks Chunkloader and several Magazines from Modern Warfare missing

### ISSUE THREAD

**Issue by wcarroll4** [scalda/FoolCraft#857]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description

Whenever I attempt to load the 2.5.1 version of Foolcraft, it reports that the ChickenChunks Chunk Loader has been removed, as well as several of the Modern Warfare weapon magazines. Can anyone confirm whether this is intentional, or an installation issue on my end? I very much appreciate the help.

## Reproduce Steps

Install version 2.5.1 from version 2.4 and try to run the game

**Comment by scalda** [comment]
Chicken chunks has been removed in favour of witching gadgets

As for the MW guns this happens because the mod changes things around with
its guns and stuff

On 13 Nov 2017 00:51, "wcarroll4" <notifications@github.com> wrote:


   - I am running the latest version of FoolCraft
   - I am running FoolCraft via Curse/Twitch Launcher
   - I can reproduce this issue consistently
      - In single player
      - In multiplayer
   - I have searched for this issue previously and it was either (1) not
   previously reported, or (2) previously fixed and I'm having the same
   problem.
   - I am crashing and can provide my crash report(s)

SUGGESTION/HELP

   - I would like to propose an additional mod, config change, custom
   recipe, etc.
   - I am requesting help with installing or running the pack

Issue Description

Whenever I attempt to load the 2.5.1 version of Foolcraft, it reports that
the ChickenChunks Chunk Loader has been removed, as well as several of the
Modern Warfare weapon magazines. Can anyone confirm whether this is
intentional, or an installation issue on my end? I very much appreciate the
help.
Reproduce Steps

Install version 2.5.1 from version 2.4 and try to run the game
Additional Information

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scalda/FoolCraft/issues/857>, or mute the thread

**Comment by wcarroll4** [comment]
Roger that. Thank you for the update and all the work you all do on the modpack!
