### ISSUE TITLE
Creosote oil texture/rancher broken

### ISSUE THREAD

**Issue by Vertigo81** [scalda/FoolCraft#900]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Creosote Oil's texture is broken (pink/black "missing" texture), which is no big deal.  But the liquid also seems to jam up the mine factory reloaded rancher.  It won't pipe out with conduits (but I CAN get it out with an enderio tank set to Pull, so go figure)

But, it also won't seem to go into a filter, so so far it needs to be processed in a totally different system than other fluids.

**Comment by BrisingrAerowing** [comment]
This happens when IE is added to a world that already has Creosote oil from another mod, as a number of other mods use it instead of their own (Railcraft).

See BluSunrise/ImmersiveEngineering#2332 for more info and a fix (Use an NBT editor to delete the Creosote Oil entry from the default fluid list in level.dat).

**Comment by scalda** [comment]
Please see here for the fix posted by blusunrize themselves https://github.com/BluSunrize/ImmersiveEngineering/issues/2332
