### ISSUE TITLE
FoolCraft 2.6 world not opening for me.

### ISSUE THREAD

**Issue by AlFirestone** [scalda/FoolCraft#922]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I had just finished setting up a new waypoint on the end and a quantum link chamber thingy in order to farm diamonds with mystical agriculture, and suddenly the next time I tried to enter the world, it crashed on me every time. I've tried deleting the chunkloaders and the waystone thing with MCEdit but it doesn't seem to work.

## Reproduce Steps
Just trying to open the world on the launcher.

## Additional Information
Here is the crash report, and thank you in advance
https://pastebin.com/gHpsGwt4

**Comment by klostrophobik** [comment]
Try deleting the dimension that your quarry is mining from.  With your server off, find the folder for DIM-9999 (or whatever number is for you if you have many players with quarries) and delete the folder.  Your quarry will create a new dimension when the server starts up.  I've had this take down my server a few times since the update to 2.4 and higher.  I've had my players disable the quarries until they're fixed.

**Comment by AlFirestone** [comment]
Thanks! I'll try it out and see what I get

**Comment by AlFirestone** [comment]
I tried out deleting the DIM-9999 folder, and I still had the same issue, here is the crash report, if anything's changed: https://pastebin.com/ELXstb1b

**Comment by scalda** [comment]
you have a bad waystone in your ae system. remove the mod load the world back up and then readd the mod
