### ISSUE TITLE
FoolCraft 2.13 Crashes before I go into a game

### ISSUE THREAD

**Issue by FooF-555** [scalda/FoolCraft#998]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Once the game starts loading up the world, it will continue loading until the message "loading terrain" is off the screen, then it will shut down the internal server.

## Reproduce Steps
Try loading a world (maybe?)

[crash-2018-05-05_15.25.44-client.txt](https://github.com/scalda/FoolCraft/files/1977016/crash-2018-05-05_15.25.44-client.txt)

**Comment by MultipleMean150** [comment]
WIthout being able to read the crash report, I could only guess.   It may be a bug with the Thaumcraft mod. You have to disable the spawn of Pechs.  This has helped others. 

Set --> B:spawn_pechs=false

You can find the config in this file: Foolcraft\config\thaumcraft.cfg

**Comment by Jaciii** [comment]
It looks like the problem is modern warfare loading the croshair... Try to make a backup of your world and then disable modern warfare and run the world. This means you mabye need to play without modern warfare. I must play without thaumcraft myself. I'm not an expert at crashreports, so I'm not sure if it works.
